---
# Location where configuration files will be stored.
config_dir: "~"

# Python installer options
python_version: 3.8.7
threads: 4

# MusicBot configuration
discord_bot_token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

spotify_client_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
spotify_client_secret: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"