---
# Location where configuration files will be stored.
config_dir: "~"

discord_bot_client_id: "XXXXXXXXXXXXXXXXXXX"
discord_bot_token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Python installer options
python_version: 3.8.7
threads: 4