---
- hosts: automated_pi
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up Zigbee2mqtt.
      ansible.builtin.import_tasks: tasks/zigbee2mqtt.yml
      when: zigbee2mqtt_enable

    - name: Set up Mosquitto.
      ansible.builtin.import_tasks: tasks/mosquitto.yml
      when: mosquitto_enable

    - name: Set up Pi-Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when: pihole_enable

    - name: Set up Portainer.
      ansible.builtin.import_tasks: tasks/portainer.yml
      when: portainer_enable

    - name: Set up Home-Assistant.
      ansible.builtin.import_tasks: tasks/home-assistant.yml