---
- name: Download MusicBot
  ansible.builtin.git:
    repo: https://github.com/Just-Some-Bots/MusicBot.git
    dest: "{{ config_dir }}/MusicBot"
    version: master
  become: false

- name: Create MusicBot config
  copy:
    src: "{{ config_dir }}/MusicBot/config/example_options.ini"
    dest: "{{ config_dir }}/MusicBot/config/options.ini"
  become: false
  
- name: Update MusicBot config
  ini_file:
    path: "{{ config_dir }}/MusicBot/config/options.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "Credentials", option: "Token", value: "{{ discord_bot_token }}" }
    - { section: "Credentials", option: "Spotify_ClientID", value: "{{ spotify_client_id }}" }
    - { section: "Credentials", option: "Spotify_ClientSecret", value: "{{ spotify_client_secret }}" }
  become: false

- name: Extract major and minor version numbers from Python version string
  set_fact:
    python_version_major_minor: "{{ python_version.split('.')[0:2] | join('.') }}"

- name: Install dependencies for MusicBot project
  become: true
  shell: |
    cd MusicBot
    sudo -H python{{ python_version_major_minor }} -m pip install --upgrade pip
    sudo -H python{{ python_version_major_minor }} -m pip install --upgrade -r requirements.txt