---
- name: Check to see if pip is already installed.
  command: "{{ pip }} --version"
  ignore_errors: true
  changed_when: false
  check_mode: false
  register: pip_installed

- name: Install pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: '0755'
  become: true
  when: pip_installed.rc != 0

- name: Run get-pip.py script
  command: "{{ python }} /tmp/get-pip.py"
  become: true
  when: pip_installed.rc != 0

# - name: Run get-pip.py script
#   command: python3.8 /tmp/get-pip.py
#   become: true
