- name: Check if Python {{ python_version }} is installed
  command: python{{ python_version | round(1) }} --version
  register: python_is_installed
  ignore_errors: true
  changed_when: false
  become: false

- name: Install dependencies
  become: true
  apt:
    name:
      - git
      - libopus-dev
      - libffi-dev
      - libsodium-dev
      - ffmpeg
      - build-essential
      - libncursesw5-dev
      - libgdbm-dev
      - libc6-dev
      - zlib1g-dev
      - libsqlite3-dev
      - tk-dev
      - libssl-dev
      - openssl
    state: present
  when: python_is_installed.rc != 0

- name: "Download python{{ python_version }}"
  get_url:
    url="https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"
    dest="/tmp/Python-{{ python_version }}.tar.xz"
  when: python_is_installed.rc != 0
  become: false

- name: "Unarchive python{{ python_version }}"
  unarchive:
    src="/tmp/Python-{{ python_version }}.tar.xz"
    dest="/tmp/"
    copy=no
    creates="/tmp/Python-{{ python_version }}"
  when: python_is_installed.rc != 0
  become: false

- name: "configure python{{ python_version }} build"
  command: ./configure
  args:
    chdir: "/tmp/Python-{{ python_version }}"
    creates: "/tmp/Python-{{ python_version }}/Makefile"
  when: python_is_installed.rc != 0
  become: false

- name: "build python{{ python_version }}"
  # not using make module to be able to use -j and creates option to fully skip step
  command: make -j{{ threads }}
  args:
    chdir: "/tmp/Python-{{ python_version }}"
    creates: "/tmp/Python-{{ python_version }}/python"
  when: python_is_installed.rc != 0
  become: false

- name: "install python{{ python_version }}"
  make:
    chdir: "/tmp/Python-{{ python_version }}"
    target: altinstall
  when: python_is_installed.rc != 0
  become: true
